GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/608b030d1dc37305ecb41b73


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Betty Bravo",
    "subscribedToChannel": "Documentasia"
}

###

DELETE http://localhost:3000/subscribers/608b0b85d37909262c3a1fb4

###

PATCH http://localhost:3000/subscribers/608b030d1dc37305ecb41b73
Content-Type: application/json

{
    "name": "Karl Max"
}